# Generated by Django 3.2.8 on 2021-10-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variatons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variatons',
            new_name='variations',
        ),
    ]
